# Generated by Django 6.0.7 on 2026-07-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='kind',
            field=models.CharField(choices=[('TEXT', '텍스트'), ('IMAGE', '이미지'), ('FILE', '파일')], max_length=20),
        ),
    ]
